apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cne-default-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: https://github.com/jmdesign3d/argo.git
    targetRevision: main
    path: apps
    helm:
      values: |
        defaultAppsRepoUrl: 'https://github.com/jmdesign3d/argo.git'
        defaultAppsTargetRev: main