apiVersion: {{ .Values.apiVersion }}
kind: Application
metadata:
  name: {{ .Values.traefikpublic.appName }}
  namespace: {{ .Values.argoNamespace }}
spec:
  destination:
    namespace: {{ .Values.traefikpublic.spec.destination.namespace }}
    server: {{ .Values.traefikpublic.spec.destination.server }}
  source:
    repoURL: {{ .Values.traefikpublic.spec.source.repoURL }}
    targetRevision: {{ .Values.traefikpublic.spec.source.targetRevision }}
    chart: {{ .Values.traefikpublic.spec.source.chart }}
    helm:
      values: |
    {{ .Files.Get "values/traefikpublic.yaml" | nindent 8 }}

  project: {{ .Values.traefikpublic.spec.project }}
  syncPolicy:
    {{- .Values.traefik.spec.syncPolicy | toYaml | nindent 4 }}
