apiVersion: v2
name: gapi-test
version: v1.0.0
description: This is the top level helm chart that is handed to argoCD to install all of our applications.
type: application
home: https://github.com/jmdesign3d/argo