apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.10.1"
    helm:
      values: |
        controller:
          allowSnippetAnnotations: true
          defaultBackend:
            enabled: true
          publishService:
            enabled: true
          config:
            limit-req-status-code: "429"
          service:
            ipFamilyPolicy: PreferDualStack
            ipFamilies:
              - IPv4
              - IPv6
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true